### ISSUE TITLE
A promise was created in a handler at webpack-internal://...react-tree-walker... but was not returned

### ISSUE THREAD

**Issue by leegee** [ctrlplusb/react-tree-walker#32]
```
Warning: a promise was created in a handler at webpack-internal:///./node_modules/react-tree-walker/dist/react-tree-walker.js:30:14 but was not returned from it, see http://goo.gl/rRqMUw
      at new Promise (/Users/lgodda/src/clp-prototype/node_modules/bluebird/js/release/promise.js:79:10)

[clp-prototype 09:31]$ yarn list webpack react-tree-walker
yarn list v1.7.0
├─ react-tree-walker@4.0.2
└─ webpack@4.8.3

node -v
v8.9.4
```

Thanks!

**Comment by ctrlplusb** [comment]
Hey @leegee 

I would ignore this warning from bluebird. I use a copied version of `p-reduce` which does some fanciful work which seems to trigger this error, although the behaviour is intentional within this implementation. 

The warning is referring to this line: https://github.com/ctrlplusb/react-tree-walker/blob/b6c594f5e2b25aa5625a6046ce0f241eb570cd8f/src/index.js#L30

Hopefully you can disable the warning for this instance?

**Comment by leegee** [comment]
Thank you!
